;; microservice-factory - A project template generated by ahungry-fleece
;; Copyright (C) 2016 Your Name <microservice-factory@example.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; microservice-factory.lib.stub.lisp

(in-package #:cl-user)

(defpackage mf.lib.parser
  (:use :cl
        :cl-ppcre
        :af.lib.io
        :af.lib.hashy)
  (:export
   :echo))

(in-package #:mf.lib.parser)

(defvar example-dir "~/src/lisp/microservice-factory/examples")
(defvar int-file (format nil "~a/integer/blueprint.yml" example-dir))
(defvar int-template (format nil "~a/integer/typescript/repository.ts" example-dir))

(defun to-bp (file)
  "Parse a file, and return the 'blueprint' hash."
  (af.lib.hashy:hash-from-yaml-file file))

(defvar blueprint (to-bp int-file))

(defstruct props name type)
(defstruct def name sql props)

(defmethod build-props ((obj def))
  (mapcar
   (lambda (p) (make-props
                :name (ref "#/name" p)
                :type (ref "#/type" p)))
   (def-props obj)))

(defun build-def (bp-def)
  "We expect a name, some sql (get) and some props."
  (let ((obj (make-def
              :name (ref "#/name" bp-def)
              :sql (ref "#/sql" bp-def)
              :props (ref "#/props" bp-def))))
    (setf (def-props obj) (build-props obj))
    obj))

(defun parse-defs (bp)
  (mapcar #'build-def (ref "#/defs" bp)))

(defmethod to-model-init-props ((p props))
  "Spit out the repo props."
  (format nil "      ~@(~a~)(o['~a'])~%"
          (props-type p)
          (props-name p)))

(defmethod to-model-props ((p props))
  "Spit out the repo props."
  (format nil "    public ~a: ~a = undefined,~%"
          (props-name p)
          (props-type p)))

(defmethod to-typescript ((obj def))
  "Convert an object definition into a useful typescript rendition."
  (let ((tpl (file-get-contents int-template)))
    (setf tpl (regex-replace-all "Stub" tpl (def-name obj)))
    (setf tpl (regex-replace-all "__SQL__" tpl (def-sql obj)))
    (setf tpl (regex-replace-all
               ".*//propsFromSql" tpl
               (mapcar #'to-model-init-props (def-props obj))))
    (setf tpl (regex-replace-all ".*//props" tpl (mapcar #'to-model-props (def-props obj))))
    tpl))

(defun echo (input)
  input)

;;; "microservice-factory.lib.stub" goes here. Hacks and glory await!
